/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        error: "#ba1a1a",
        "surface-bright": "#f7fafc",
        "on-secondary-container": "#007165",
        "tertiary-fixed": "#eddcff",
        "inverse-on-surface": "#eef1f3",
        "on-surface": "#181c1e",
        "on-secondary-fixed": "#00201c",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f1f4f6",
        "inverse-primary": "#a5cdda",
        "on-tertiary-container": "#d8c2f2",
        "on-primary-fixed": "#001f27",
        "on-primary-container": "#a9d1df",
        "tertiary-container": "#5f4e77",
        "surface-dim": "#d7dadc",
        surface: "#f7fafc",
        "tertiary-fixed-dim": "#d3beee",
        "primary-fixed": "#c0e9f7",
        "error-container": "#ffdad6",
        "secondary-fixed": "#8df5e4",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#8df5e4",
        "on-primary-fixed-variant": "#244c57",
        "outline-variant": "#bfc8c8",
        "on-tertiary-fixed": "#231339",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#a5cdda",
        "secondary-fixed-dim": "#70d8c8",
        "on-secondary": "#ffffff",
        primary: "#205E61",
        "primary-container": "#345b66",
        "on-surface-variant": "#404849",
        "on-secondary-fixed-variant": "#005048",
        outline: "#707979",
        "on-tertiary": "#ffffff",
        "surface-container": "#ebeef0",
        tertiary: "#47375e",
        "on-tertiary-fixed-variant": "#503f67",
        background: "#f7fafc",
        "on-background": "#181c1e",
        secondary: "#006b5f",
        "surface-tint": "#3d6470",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e5e9eb",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
